### ISSUE TITLE
xbps-install gpgmepp segfaults

### ISSUE THREAD

**Issue by vtoc** [voidlinux/xbps#264]
Got it tracking down dependencies in the stack of xbps-install libreoffice

```(gdb) run
Starting program: /usr/bin/xbps-install gpgmepp
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120     ../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00007ffff77857c5 in prop_string_create_cstring_nocopy (str=str@entry=0x0)
    at portableproplib/prop_string.c:190
#2  0x00007ffff7787ada in prop_dictionary_set_cstring_nocopy (
    dict=dict@entry=0x5555560fa600, key=key@entry=0x7ffff77a14c3 "transaction", 
    cp=cp@entry=0x0) at portableproplib/prop_dictionary_util.c:218
#3  0x00007ffff779c0d5 in xbps_dictionary_set_cstring_nocopy (d=d@entry=0x5555560fa600, 
    s=s@entry=0x7ffff77a14c3 "transaction", ss=ss@entry=0x0) at proplib_wrapper.c:734
#4  0x00007ffff779a32b in find_repo_deps (xhp=xhp@entry=0x7fffffffdc40, 
    unsorted=unsorted@entry=0x5555571d3fd0, 
    pkg_rdeps_array=pkg_rdeps_array@entry=0x5555560fbcd0, pkg_provides=0x0, 
    curpkg=0x5555560fbc80 "gpgmepp-1.9.0_2", depth=depth@entry=0x7fffffffd75e)
    at repo_pkgdeps.c:363
#5  0x00007ffff779aa5e in xbps_repository_find_deps (xhp=xhp@entry=0x7fffffffdc40, 
    unsorted=unsorted@entry=0x5555571d3fd0, repo_pkgd=repo_pkgd@entry=0x5555560fb840)
    at repo_pkgdeps.c:396
#6  0x00007ffff778f162 in xbps_transaction_prepare (xhp=xhp@entry=0x7fffffffdc40)
    at transaction_dictionary.c:288
#7  0x0000555555556361 in exec_transaction (xhp=0x7fffffffdc40, maxcols=90, 
    yes=<optimized out>, drun=<optimized out>) at transaction.c:306
#8  0x0000555555555c06 in main (argc=2, argv=0x7fffffffe5e8) at main.c:262
```

Frame 4 has at least some intresting data left:

```(gdb) frame 4
#4  0x00007ffff779a32b in find_repo_deps (xhp=xhp@entry=0x7fffffffdc40, unsorted=unsorted@entry=0x5555571d3fd0, pkg_rdeps_array=pkg_rdeps_array@entry=0x5555560fbcd0, 
    pkg_provides=0x0, curpkg=0x5555560fbc80 "gpgmepp-1.9.0_2", depth=depth@entry=0x7fffffffd75e) at repo_pkgdeps.c:363
(gdb) info args
xhp = 0x7fffffffdc40
unsorted = 0x5555571d3fd0
pkg_rdeps_array = 0x5555560fbcd0
pkg_provides = 0x0
curpkg = 0x5555560fbc80 "gpgmepp-1.9.0_2"
depth = 0x7fffffffd75e
(gdb) info locals
curpkgd = <optimized out>
obj = <optimized out>
iter = 0x5555571d4ef0
curpkgrdeps = <optimized out>
curpkgprovides = <optimized out>
state = XBPS_PKG_STATE_INSTALLED
reqpkg = 0x5555560fbd40 "gpgme>=1.9.0_2"
pkgver_q = 0x5555560faa00 "gpgme-1.9.0_2"
reason = 0x0
pkgname = 0x5555571d44d0 ""
reqpkgname = <optimized out>
rv = <optimized out>
foundvpkg = <optimized out>
__PRETTY_FUNCTION__ = "find_repo_deps"
```

**Comment by vtoc** [comment]
checked the gpgme version on my system, it was an older version that was on hold

```
$ xbps-query gpgme
architecture: x86_64
build-date: 2015-01-21 18:37 EET
filename-sha256: b7b3d539ebf529ff6024f5e64ea7e46a812b3d1546cabff291da302fd9e234c3
filename-size: 118KB
hold: yes
homepage: http://www.gnupg.org/related_software/gpgme/
install-date: 2015-06-08 14:14 EEST
installed_size: 525KB
license: GPL-2
maintainer: Juan RP <xtraeme@gmail.com>
metafile-sha256: 867e0c4f04616c060d2e929173241c1b8626b0145a330d6090cd78f4618ac886
pkgver: gpgme-1.5.3_2
repository: /home/xbps/void-packages/hostdir/binpkgs
shlib-provides:
        libgpgme-pthread.so.11
        libgpgme.so.11
shlib-requires:
        libassuan.so.0
        libgpg-error.so.0
        libc.so.6
        libpthread.so.0
        ld-linux-x86-64.so.2
short_desc: GnuPG Made Easy
state: installed
```

Updating the package to the current version solved the issue for me, however i think the code should handle that

**Comment by Duncaen** [comment]
This is fixed in master https://github.com/voidlinux/xbps/issues/143 (https://github.com/voidlinux/xbps/commit/067687ce28fa7a2869f94fe6adab5cdf74c278d3).
